### PR TITLE
rio-tiler v7 compatibility

### LINKED ISSUE #81: Update to rio-tiler v7
Would it please be possible to get a new release that is compatible with rio-tiler v7?

### PR DESCRIPTION
**Pull request by JackDunnNZ**
Looking over the changelog from rio-tiler v7, I think this was the only change that needed to be carried over. I copied over the relevant changelog entries too but can remove them if you think they are redundant.

Fixes #81

### CODE REVIEW

**Comment by JackDunnNZ** [comment]
@vincentsarago sorry for the ping as I know you are busy

**Comment by vincentsarago** [comment]
Yeah sorry @JackDunnNZ , super busy and travelling a lot lately :-(

**Comment by JackDunnNZ** [comment]
@vincentsarago another gentle reminder if you have the chance to review this please

**Comment by JackDunnNZ** [comment]
Thank you!

**Pull request merged**
