### PR TITLE
Fix sentinel 2 cog prefix

### PR DESCRIPTION
**Pull request by kylebarron**
```
with S2COGReader('S2B_12SYJ_20200901_0_L2A') as scene:
    pass
```
currently errors with a `NoSuchKey` exception. This is because the directory structure of the bucket changed

This key exists:
```
s3://sentinel-cogs/sentinel-s2-l2a-cogs/12/S/YJ/2020/9/S2B_12SYJ_20200901_0_L2A/
```

### CODE REVIEW

**Comment by vincentsarago** [comment]
@kylebarron can you update the tests please!

**Comment by vincentsarago** [comment]
👋 @matthewhanson will there be any other change in the bucket? 

side question: are the stac items up to date?

**Comment by matthewhanson** [comment]
@vincentsarago @kylebarron The only change going forward will be the removal of the older prefix that starts with `acquisitionYear`. 

The STAC records should be up to date, although in the next few weeks there will be some small fixes and updates to the metadata, I don't have a complete list of those yet.

**Comment by vincentsarago** [comment]
thanks @matthewhanson that's great. 

from rio-tiler-pds POV metadata change won't impact us because we only use the `assets` and `bbox` info https://github.com/cogeotiff/rio-tiler-pds/blob/master/rio_tiler_pds/sentinel/aws/sentinel2.py#L232-L235

**Review by vincentsarago — APPROVED** [review]

**Pull request merged**
